functional:
  - Пользователь должен иметь возможность зарегистрироваться через электронную почту
  - Пользователь должен иметь возможность зарегистрироваться через Github
  - Пользователь должен иметь возможность зарегистрироваться через Discord
  - Пользователь должен иметь возможность авторизоваться через почту
  - Пользователь должен иметь возможность авторизоваться через Github
  - Пользователь должен иметь возможность авторизоваться через Discord
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность отменить созданную игру
  - Пользователь должен иметь возможность подключиться к игре
  - Пользователь должен иметь возможность выбрать уровень сложности
  - Пользователь должен иметь возможность играть с ботом
  - Пользователь должен иметь возможность пригласить другого игрока
  - Пользователь должен иметь возможность продолжить игру, если соперник отключился
  - Пользователь должен иметь возможность выбрать язык программирования Python, Java, Go, JavaScript, PHP, Ruby, Kotlin
  - Пользователь должен иметь возможность просматривать общую статистику игр
  - Пользователь должен иметь возможность просматривать собственную статистику
  - Пользователь должен иметь возможность просматривать рейтинг пользователей
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров Google Chrome, Mozilla Firefox, Safari
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Сайт должен быть доступен 24 часа в сутки
  - Сайт должен обеспечивать честную победу пользователя
  - При потере соединения пользователь должен иметь возможность повторно подключиться к игре в любой момент, пока игра не закончена
  - Пользователь должен иметь возможность оставить обратную связь
  - Пользователю должен быть доступен список игроков, находящихся онлайн
  - Пользователь должен иметь возможность участвовать в турнирах
  - Пользователь должен иметь возможность смотреть историю игр
  - Пользователь должен иметь возможность видеть код соперника в режиме онлайн
  - Пользователю должна быть доступна кнопка для проверки своего решения
  - Пользователь должен иметь возможность увидеть результат игры
  - Пользователю должен быть доступен чат для каждой игры
  - Пользователю должен быть доступен общий чат
  - У пользователя должна быть возможность сдаться
